// code generated by [generate-resource-dart-code] vscode-extension.
class AssetsImages {
  static const authenticItalianPastaJpg = 'assets/images/authentic-italian-pasta.jpg';
  static const cheesecakeWithStrawberryTableJpg = 'assets/images/cheesecake-with-strawberry-table.jpg';
  static const classicLasagnaWithBologneseSauceJpg = 'assets/images/classic-lasagna-with-bolognese-sauce.jpg';
  static const deliciousDonutsJpg = 'assets/images/delicious-donuts.jpg';
  static const freshRedStrawberriesMellowDeliciousBerriesWithCakesLightJpg = 'assets/images/fresh-red-strawberries-mellow-delicious-berries-with-cakes-light.jpg';
  static const frontViewChocolateDessertGlassWithStrawJpg = 'assets/images/front-view-chocolate-dessert-glass-with-straw.jpg';
  static const homemadeChocolateCakeWithRaspberrySauceWhippedCreamGeneratedByArtificialIntelligenceJpg = 'assets/images/homemade-chocolate-cake-with-raspberry-sauce-whipped-cream-generated-by-artificial-intelligence.jpg';
  static const manviMathurQ2BlVtHOcAkUnsplashJpg = 'assets/images/manvi-mathur-Q2BlVtHOcAk-unsplash.jpg';
  static const margheritaPizzaJpg = 'assets/images/MargheritaPizza .jpg';
  static const oneJpg = 'assets/images/one.jpg';
  static const sideViewPieceHoneyCakeJpg = 'assets/images/side-view-piece-honey-cake.jpg';
  static const spaghettiWithMixedIngredientsWhitePlateJpg = 'assets/images/spaghetti-with-mixed-ingredients-white-plate.jpg';
  static const starterImageJpg = 'assets/images/starter-image.jpg';
  static const threeJpg = 'assets/images/three.jpg';
  static const topViewCheesyPastaWhitePlateJpg = 'assets/images/top-view-cheesy-pasta-white-plate.jpg';
  static const topViewTastyItalianPastaWithMeatballsDarkBlueBackgroundJpg = 'assets/images/top-view-tasty-italian-pasta-with-meatballs-dark-blue-background.jpg';
  static const twoJpg = 'assets/images/two.jpg';
}

class AssetsSvgs {

}

